config/routes.rb
Rails.application.routes.draw do
root "people#index"
resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def index
    @people = Person.all
  end

  def show
  end

  def edit
  end
  
  def update
    if @person.update(person_params)
      redirect_to people_path
    else
      render :edit
    end
  end
  
  def new
    @person = Person.new
  end
  
  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to people_path
    else
      render :new
    end

  end

  def destroy
    @person.destroy
    redirect_to people_path
  end


  private
  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:name, :avatar, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CssFrameworks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  
  <div class="ui container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: @person, local: true, class: "ui form") do |f| %>
  <div class = "field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Full Name"%>
  </div>
  <br>
  <div class = "field">
    <%= f.label :avatar %>
    <%= f.text_field :avatar, required: true, placeholder: "Avatar" %>
  </div>
  <br>
  <div class = "field">
    <%= f.label :email %>
    <%= f.text_field :email, required: true, placeholder: "Email" %>
  </div>
  <br>
  <button class= "ui primary button" type="submit"> Submit </button>
  <%# <%= link_to "Cancel", person_path(@person.id)%>
<%end%>

app/views/people/edit.html.erb
<h1 class = "ui header">Edit Person</h1>

<%= render "form" , person: @person %>

app/views/people/index.html.erb
<h1 class="ui header">People</h1>
<div class = "ui button">
<i class="user icon"></i><%= link_to 'New Person', new_person_path %>
</div>
<div class="ui divider"></div>

<div class="ui grid">
  <% @people.each do |person| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
      <div class="ui card">
        <div class="image">
            <img src="<%= person.avatar %>" />
        </div>
        <div class="content">
          <%= link_to "#{person.name}", person, class: "header" %>
        </div>
        <div class="extra content">
          <div class="ui two buttons">
            <div class="ui basic green button">
              <%= link_to 'Edit', edit_person_path(person) %>
            </div>
            <div class="ui basic red button">
              <%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/people/new.html.erb
<h1 class = "ui header">Add A New Person</h1>

<%= render "form" , person: @person %>

app/views/people/show.html.erb
<div class = "ui card">
  <div class ="image">
    <img src = "<%=@person.avatar%>" />
  </div>
  <div class = "content">
      <p class="header">
        <%= @person.name %>
      </p>
      <div class = "description">
        <%= @person.email %>
      </div>
  </div>

  <div class = "extra content">
   <%= link_to "Edit", edit_person_path(@person) %>  |
   <%= link_to "Back", people_path %>
</div>